vkxml.py: Handle VkBaseOutStructure circular reference
VkBaseOutStructure was added to vk.xml in v1.3.213

VkBaseOutStructure struct contains a pointer to another
VkBaseOutStructure which causes vkxml.py to end up in a stack overflow
trying to traverse in variable attributes.

File "/home/justonli/Workspace/venus-protocol/vkxml.py", line 307, in set_attribute
  var.ty.set_attribute(key, val)
  [Previous line repeated 991 more times]
RecursionError: maximum recursion depth exceeded

Handle it as a special case in set_attribute and just return

Signed-off-by: Juston Li <justonli@chromium.org>